# Generated by Django 2.1.5 on 2019-02-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва піци')),
                ('short_description', models.CharField(max_length=30, verbose_name='Короткий опис')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна')),
            ],
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Піцерія'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizzashop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.PizzaShop'),
        ),
    ]
