# Generated by Django 2.1.5 on 2019-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190211_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Піца', 'verbose_name_plural': 'Піци'},
        ),
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'Піцерія', 'verbose_name_plural': 'Піцерії'},
        ),
    ]
