# Generated by Django 2.1.5 on 2019-02-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20190211_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['price'], 'verbose_name': 'Піца', 'verbose_name_plural': 'Піци'},
        ),
        migrations.RenameField(
            model_name='pizzashop',
            old_name='descriptions',
            new_name='description',
        ),
    ]
