# Generated by Django 2.1.5 on 2019-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Піццерія')),
                ('descriptions', models.TextField(verbose_name='Опис')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('url', models.URLField(verbose_name='Інтернет-адреса піцерії')),
            ],
        ),
    ]
